# Generated by Django 4.1.1 on 2022-11-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
